### ISSUE TITLE
api isn't fetching movies and tvs any more

### ISSUE THREAD

**Issue by luslucifer** [cool-dev-guy/vidsrc-api#8]
I believe JW Player has recently been updated.

**Comment by Inside4ndroid** [comment]
same issue here !

**Comment by cool-dev-guy** [comment]
The issue is fixed in the latest commit.thanks for reporting the issue.

**Comment by cool-dev-guy** [comment]
Please re-open this issue if the problem still exist.

**Comment by Inside4ndroid** [comment]
the issue still persists and nothing is returned ?

i have re-deployed on vercel and run locally but nothing has changed and reseults are still empty.

![Screenshot 2024-03-31 093251](https://github.com/cool-dev-guy/vidsrc-api/assets/65467186/f45713e3-434a-4aed-8e4c-2a0da9443fa9)
